apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: test-nodeapp
  namespace: jephilli
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - env:
        - name: env
          value: development
        image: quay.io/karthik_jk/test-nodeapp@sha256:bebfe817b032d37a8c040c9719c03842df23f6bb101b600e83e68655cd570fa8
        name: container-image
        resources: {}
status: {}
